export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"
export const VERIFY = "VERIFY"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_ERROR = "VERIFY_ERROR"
export const LOGOUT = "LOGOUT"